version: 0.1

env:
  variables:
    ACTION: create
phases:
  install:
    commands:
      - echo '#!/bin/bash' > /usr/local/bin/ok; echo 'if [[ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]]; then exit 1; else exit 0; fi' >> /usr/local/bin/ok; chmod +x /usr/local/bin/ok
  pre_build:
    on-failure: ABORT
    commands:
      - |
        if [ ${ACTION} = "creat" ]; then
          echo "Action ${ACTION} is not allowed!";
        else
          exit 1;
        fi
  build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"securetest1\" --password=\"Arseetha@12\""
